version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/Gowtham-PMS:1"
        LoadBalancerInfo:
          ContainerName: "Gow-Auth-Container"
          ContainerPort: "8080"
          PlatformVersion: "LATEST"
